import { useState, useEffect, useCallback } from 'react'
import { useShortcutsStore } from '../../stores/shortcutsStore'
import { formatKeybinding } from '../../utils/shortcutMatcher'
import type { SystemInfo } from '../../../shared/types'
import { useMobileMode } from '../../hooks/useMobileMode'
import { tint } from '../../utils/colorMix'

const GLOBAL_SHORTCUT_ACTIONS = new Set(['quick_chat', 'quick_voice', 'show_app', 'stop_tts'])

/** Check if the key part of a keybinding contains non-ASCII chars (e.g. ², §, µ) that Hyprland may not recognize. */
function hasSpecialKey(keybinding: string): boolean {
  const parts = keybinding.split('+')
  const key = parts[parts.length - 1]
  return /[^\x20-\x7E]/.test(key)
}

function formatActionName(action: string): string {
  return action
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function keyEventToAccelerator(e: KeyboardEvent): string | null {
  const parts: string[] = []
  if (e.ctrlKey) parts.push('Ctrl')
  if (e.metaKey) parts.push('Super')
  if (e.altKey) parts.push('Alt')
  if (e.shiftKey) parts.push('Shift')

  const key = e.key
  if (['Control', 'Meta', 'Alt', 'Shift', 'Super'].includes(key)) return null

  if (key === ' ' || key === '\u00A0') {
    // '\u00A0' = non-breaking space generated by Option+Space on macOS
    parts.push('Space')
  } else if (key.length === 1) {
    parts.push(key.toUpperCase())
  } else if (key === 'Escape') {
    return null
  } else {
    parts.push(key)
  }

  return parts.join('+')
}

const DEFAULT_KEYBINDINGS: Record<string, string> = {
  new_conversation: 'Ctrl+N',
  send_message: 'Enter',
  stop_generation: 'Escape',
  toggle_sidebar: 'Ctrl+B',
  toggle_panel: 'Ctrl+J',
  focus_search: 'Ctrl+K',
  settings: 'Ctrl+,',
  voice_input: 'Ctrl+Shift+V',
  quick_chat: 'Alt+Space',
  quick_voice: 'Alt+Shift+Space',
  show_app: 'Super+A',
  stop_tts: 'Ctrl+Shift+T',
}

export function ShortcutSettings() {
  const { shortcuts, loadShortcuts, updateShortcut } = useShortcutsStore()
  const [recordingId, setRecordingId] = useState<number | null>(null)
  const [conflict, setConflict] = useState<string | null>(null)
  const [sessionType, setSessionType] = useState<SystemInfo['sessionType'] | null>(null)
  const mobile = useMobileMode()

  useEffect(() => {
    loadShortcuts()
    window.agent.system.getInfo().then((info) => setSessionType(info.sessionType)).catch(() => {})
  }, [loadShortcuts])

  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (recordingId === null) return

      e.preventDefault()
      e.stopPropagation()

      if (e.key === 'Escape') {
        setRecordingId(null)
        setConflict(null)
        return
      }

      const accelerator = keyEventToAccelerator(e)
      if (!accelerator) return

      const existing = shortcuts.find(
        (s) => s.keybinding === accelerator && s.id !== recordingId
      )
      if (existing) {
        setConflict(formatActionName(existing.action))
        return
      }

      updateShortcut(recordingId, accelerator)
      setRecordingId(null)
      setConflict(null)
    },
    [recordingId, shortcuts, updateShortcut]
  )

  useEffect(() => {
    if (recordingId !== null) {
      window.addEventListener('keydown', handleKeyDown, true)
      return () => window.removeEventListener('keydown', handleKeyDown, true)
    }
  }, [recordingId, handleKeyDown])

  const appShortcuts = shortcuts.filter((s) => !GLOBAL_SHORTCUT_ACTIONS.has(s.action))
  const globalShortcuts = shortcuts.filter((s) => GLOBAL_SHORTCUT_ACTIONS.has(s.action))

  if (mobile) {
    return (
      <div className="flex flex-col gap-4">
        <div
          className="rounded px-3 py-3 text-sm leading-relaxed"
          style={{
            backgroundColor: 'var(--color-bg)',
            color: 'var(--color-text-muted)',
          }}
        >
          Keyboard shortcuts require a physical keyboard and are not available in web mode.
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      {/* App shortcuts */}
      <ShortcutTable
        shortcuts={appShortcuts}
        recordingId={recordingId}
        conflict={conflict}
        onRecord={(id) => { setConflict(null); setRecordingId(recordingId === id ? null : id) }}
      />

      {/* Global shortcuts */}
      {globalShortcuts.length > 0 && (
        <div className="flex flex-col gap-3">
          <h4
            className="text-xs font-semibold uppercase tracking-wide pt-2"
            style={{ color: 'var(--color-text-muted)' }}
          >
            Global Shortcuts
          </h4>

          {sessionType === 'wayland' && (
            <div
              className="rounded px-3 py-2 text-xs leading-relaxed"
              style={{
                backgroundColor: 'color-mix(in srgb, var(--color-warning, #f59e0b) 15%, transparent)',
                color: 'var(--color-text)',
                border: '1px solid color-mix(in srgb, var(--color-warning, #f59e0b) 30%, transparent)',
              }}
              role="alert"
            >
              <strong>Wayland session detected.</strong> Global shortcuts use the XDG Desktop Portal.
              If shortcuts don&apos;t work, verify your compositor supports{' '}
              <code className="text-xs">org.freedesktop.portal.GlobalShortcuts</code>{' '}
              (KDE Plasma 5.27+, Hyprland, GNOME 47+).
            </div>
          )}

          <ShortcutTable
            shortcuts={globalShortcuts}
            recordingId={recordingId}
            conflict={conflict}
            onRecord={(id) => { setConflict(null); setRecordingId(recordingId === id ? null : id) }}
            warnSpecialKeys={sessionType === 'wayland'}
          />
        </div>
      )}

      {/* Reset button */}
      <div className="pt-2">
        <button
          className="px-4 py-2 rounded text-sm font-medium transition-opacity hover:opacity-80"
          style={{
            backgroundColor: 'var(--color-deep)',
            color: 'var(--color-text)',
          }}
          onClick={async () => {
            for (const shortcut of shortcuts) {
              const defaultKey = DEFAULT_KEYBINDINGS[shortcut.action]
              if (defaultKey && shortcut.keybinding !== defaultKey) {
                await updateShortcut(shortcut.id, defaultKey)
              }
            }
          }}
        >
          Reset All to Defaults
        </button>
      </div>
    </div>
  )
}

function ShortcutTable({
  shortcuts,
  recordingId,
  conflict,
  onRecord,
  warnSpecialKeys,
}: {
  shortcuts: { id: number; action: string; keybinding: string }[]
  recordingId: number | null
  conflict: string | null
  onRecord: (id: number) => void
  warnSpecialKeys?: boolean
}) {
  return (
    <div className="flex flex-col">
      {/* Header */}
      <div
        className="flex items-center py-2 border-b text-xs font-medium"
        style={{ color: 'var(--color-text-muted)', borderColor: tint('--color-text-muted', 20) }}
      >
        <span className="flex-1">Action</span>
        <span className="w-48">Keybinding</span>
        <span className="w-20 text-right">Edit</span>
      </div>

      {/* Rows */}
      {shortcuts.map((shortcut) => (
        <div
          key={shortcut.id}
          className="flex items-center py-3 border-b"
          style={{ borderColor: tint('--color-text-muted', 10) }}
        >
          <span
            className="flex-1 text-sm"
            style={{ color: 'var(--color-text)' }}
          >
            {formatActionName(shortcut.action)}
          </span>
          <span className="w-48">
            {recordingId === shortcut.id ? (
              <span className="flex flex-col gap-1">
                <span
                  className="text-xs italic"
                  style={{ color: 'var(--color-primary)' }}
                >
                  Press a key combination...
                </span>
                {conflict && (
                  <span
                    className="text-xs"
                    style={{ color: 'var(--color-warning)' }}
                  >
                    Conflicts with: {conflict}
                  </span>
                )}
              </span>
            ) : (
              <span className="flex flex-col gap-1">
                <span
                  className="inline-block px-2 py-1 rounded text-xs font-mono"
                  style={{
                    backgroundColor: 'var(--color-bg)',
                    color: 'var(--color-text)',
                    border: '1px solid var(--color-text-muted)',
                    opacity: 0.3,
                  }}
                >
                  {formatKeybinding(shortcut.keybinding)}
                </span>
                {warnSpecialKeys && hasSpecialKey(shortcut.keybinding) && (
                  <span
                    className="text-[0.625rem] leading-tight"
                    style={{ color: 'var(--color-warning, #f59e0b)' }}
                  >
                    Special key — may not work with Hyprland
                  </span>
                )}
              </span>
            )}
          </span>
          <span className="w-20 text-right">
            <button
              onClick={() => onRecord(shortcut.id)}
              className={`px-2 py-1 rounded text-xs font-medium transition-opacity hover:opacity-80 ${
                recordingId === shortcut.id
                  ? 'bg-warning text-contrast'
                  : 'bg-deep text-body'
              }`}
            >
              {recordingId === shortcut.id ? 'Cancel' : 'Record'}
            </button>
          </span>
        </div>
      ))}
    </div>
  )
}
